recursion_partition: recursion_partition.o
	g++ -o recursion_partition recursion_partition.o -std=c++11

recursion_partition.o: recursion_partition.cpp
	g++ -c recursion_partition.cpp -std=c++11
run:
	./recursion_partition

clean:
	rm recursion_partition.o
